name: CommandInvoker
version: '${project.version}'
main: top.darkmine.comm.commandinvoker.CommandInvoker
api-version: '1.20'
softdepend: [ AureliumSkills ]
authors: [ wotyk ]
commands:
  cinvoker:
    description: "Reload config"
    usage: /cinvoker reload
